const ROUTINE={
 lunes:{name:'PUSH',nutrition:'Fuerza · 2300 kcal',ex:[['Press inclinado mancuernas',4,8,150],['Press convergente máquina',3,10,150],['Press militar máquina/Smith',3,8,150],['Elevaciones laterales',4,12,90],['Aperturas peck-deck/polea',2,15,90],['Tríceps polea',3,10,120],['Tríceps sobre cabeza',3,12,120]]},
 martes:{name:'PULL',nutrition:'HC alto · 2450 kcal',ex:[['Jalón pronado abierto',4,8,150],['Remo con pecho apoyado',4,10,150],['Jalón neutro/cerrado',3,10,150],['Jalón brazos rectos',2,12,90],['Reverse peck-deck',4,15,90],['Curl inclinado',3,10,120],['Curl Scott',3,12,120]]},
 miércoles:{name:'LEGS',nutrition:'HC alto · 2450 kcal',ex:[['Hack / prensa',4,8,150],['Búlgara',3,10,150],['Extensión cuádriceps',3,12,90],['Curl femoral',4,10,150],['Hip thrust',3,10,150],['Gemelos',4,15,90],['Rueda abdominal',4,10,90]]},
 jueves:{name:'UPPER',nutrition:'Fuerza · 2300 kcal',ex:[['Press plano mancuernas',4,8,150],['Jalón',3,10,150],['Press inclinado/convergente',3,10,150],['Remo máquina/polea',4,10,150],['Elevaciones laterales',4,15,90],['Reverse peck-deck',3,15,90],['Curl bíceps',3,10,120],['Tríceps polea',3,10,120]]},
 viernes:{name:'LOWER + HOMBRO/BRAZO',nutrition:'HC alto · 2450 kcal',ex:[['Prensa',3,10,150],['Curl femoral',3,10,150],['Hip thrust',3,10,150],['Extensión cuádriceps',2,15,90],['Elevaciones laterales',4,15,90],['Curl martillo',3,12,120],['Tríceps cuerda',3,12,120],['Gemelos',3,15,90],['Rueda abdominal',3,10,90]]},
 sábado:{name:'DESCANSO',nutrition:'Descanso · 2150 kcal',ex:[]},domingo:{name:'DESCANSO',nutrition:'Descanso · 2150 kcal',ex:[]}
};
const days=['domingo','lunes','martes','miércoles','jueves','viernes','sábado'];
let view='today',selected=days[new Date().getDay()];
const HISTORY_KEY='jcTrainingHistoryV1';
const load=()=>JSON.parse(localStorage.getItem(HISTORY_KEY)||'{}');
const save=x=>localStorage.setItem(HISTORY_KEY,JSON.stringify(x));
const iso=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
function allFor(name){const h=load(),all=[];Object.entries(h).forEach(([d,s])=>Object.entries(s.ex||{}).forEach(([n,v])=>{if(n===name&&v.completed)all.push([d,v])}));all.sort((a,b)=>a[0].localeCompare(b[0]));return all}
function lastFor(name){const a=allFor(name);return a.length?a[a.length-1]:null}
function weightArray(v,sets){if(Array.isArray(v?.weights))return Array.from({length:sets},(_,i)=>v.weights[i]??v.weights[0]??'');const old=v?.weight??'';return Array(sets).fill(old)}
function displayWeights(v){const w=(v.weights||[]).filter(x=>String(x).trim()!=='');if(!w.length&&v.weight)return `${v.weight}`;if(!w.length)return'-';return w.every(x=>String(x)===String(w[0]))?`${w[0]}`:w.join('/')}
function topWeight(v){const w=(v.weights||[]).map(Number).filter(Number.isFinite);if(w.length)return Math.max(...w);const x=Number(v.weight);return Number.isFinite(x)?x:0}
function advice(ex,last){if(!last)return 'Primera sesión: usa una carga con la que completes el objetivo dejando RIR 1–2.';const v=last[1],ok=(v.reps||[]).length===ex[1]&&(v.reps||[]).every(r=>Number(r)>=ex[2])&&Number(v.rir||0)>=1;return ok?'✓ Objetivo completado: prueba el siguiente incremento de peso disponible.':'→ Mantén la carga hasta completar todas las series con buena técnica y RIR 1–2.'}
let timerInt=null;
function startTimer(sec,id){clearInterval(timerInt);let t=sec;const el=document.getElementById(id);if(!el)return;const draw=()=>el.textContent=`⏱ ${Math.floor(t/60)}:${String(t%60).padStart(2,'0')}`;draw();timerInt=setInterval(()=>{t--;draw();if(t<=0){clearInterval(timerInt);el.textContent='✓ Descanso terminado';navigator.vibrate?.(250)}},1000)}
function exerciseState(date,day,name,sets,target){const h=load(),saved=h?.[date]?.ex?.[name];if(saved)return {...saved,weights:weightArray(saved,sets),reps:Array.from({length:sets},(_,i)=>saved.reps?.[i]??target),done:Array.from({length:sets},(_,i)=>!!saved.done?.[i])};const last=lastFor(name),base=last?.[1];return {weights:weightArray(base,sets),reps:Array(sets).fill(target),done:Array(sets).fill(false),rir:'',completed:false}}
function storeExercise(date,day,name,state){const h=load();if(!h[date])h[date]={day,ex:{}};h[date].day=day;h[date].ex[name]=state;save(h)}
function sessionProgress(day,date){const r=ROUTINE[day],h=load(),s=h?.[date]?.ex||{};const done=r.ex.filter(e=>s[e[0]]?.completed).length;return {done,total:r.ex.length}}
function renderToday(day=selected){selected=day;const r=ROUTINE[day],date=iso(),prog=sessionProgress(day,date);setTitle('Hoy');let html=`<section class='hero'><div class='eyebrow'>${day.toUpperCase()}</div><h2>${r.name}</h2><p>${r.nutrition}</p><div class='sessionbar'><span>${prog.done}/${prog.total} ejercicios guardados</span><i style='width:${prog.total?Math.round(prog.done/prog.total*100):0}%'></i></div></section>`;
 if(!r.ex.length){html+=`<div class='card'><b>Día de descanso.</b><p class='muted'>Recuperación, paseo o LISS suave si corresponde.</p></div>`}
 r.ex.forEach((e,i)=>{const [name,sets,reps,rest]=e,last=lastFor(name),cur=exerciseState(date,day,name,sets,reps);html+=`<div class='exercise ${cur.completed?'completed':''}' data-ex='${i}'><div class='exhead'><div><h3>${name}</h3><div class='target'>Objetivo · ${sets} × ${reps}</div></div>${cur.completed?'<span class="badge">HECHO</span>':''}</div><div class='muted'>Descanso ${Math.floor(rest/60)}:${String(rest%60).padStart(2,'0')}</div>${last?`<div class='hist'>Anterior: <b>${displayWeights(last[1])} kg</b> · ${(last[1].reps||[]).join('/')||'-'} · RIR ${last[1].rir||'-'}</div>`:''}<div class='series'><div class='serieslabels'><span>Serie</span><span>Peso kg</span><span>Reps</span><span></span></div>${Array.from({length:sets},(_,s)=>`<div class='seriesrow ${cur.done[s]?'seriesdone':''}'><b>S${s+1}</b><input class='seriesinput' inputmode='decimal' data-weight='${i}:${s}' value='${cur.weights[s]??''}' placeholder='kg'><input class='seriesinput' inputmode='numeric' data-rep='${i}:${s}' value='${cur.reps[s]}'><button data-setdone='${i}:${s}' class='setbtn'>${cur.done[s]?'✓':'Hecha'}</button></div>`).join('')}</div><div class='row finishrow'><label>RIR final <input inputmode='numeric' data-rir='${i}' value='${cur.rir}' placeholder='1–2'></label><button data-timer='${i}' class='secondary'>⏱ Descanso</button><span class='timer' id='timer${i}'></span></div><button data-saveex='${i}' class='primary wide'>Guardar ejercicio</button><div class='advice'>${advice(e,last)}</div></div>`});document.getElementById('app').innerHTML=html;bind(day,date)}
function bind(day,date){const r=ROUTINE[day];function getState(i){const e=r.ex[i];return exerciseState(date,day,e[0],e[1],e[2])}function put(i,st){storeExercise(date,day,r.ex[i][0],st)}
 document.querySelectorAll('[data-weight]').forEach(x=>x.onchange=()=>{const [i,s]=x.dataset.weight.split(':').map(Number),st=getState(i);st.weights[s]=x.value;if(s===0){for(let j=1;j<st.weights.length;j++){if(!String(st.weights[j]??'').trim()){st.weights[j]=x.value;const other=document.querySelector(`[data-weight=\"${i}:${j}\"]`);if(other)other.value=x.value}}}put(i,st)});
 document.querySelectorAll('[data-rir]').forEach(x=>x.onchange=()=>{const i=Number(x.dataset.rir),st=getState(i);st.rir=x.value;put(i,st)});
 document.querySelectorAll('[data-rep]').forEach(x=>x.onchange=()=>{const [i,s]=x.dataset.rep.split(':').map(Number),st=getState(i);st.reps[s]=x.value;put(i,st)});
 document.querySelectorAll('[data-setdone]').forEach(x=>x.onclick=()=>{const [i,s]=x.dataset.setdone.split(':').map(Number),e=r.ex[i],st=getState(i);if(!String(st.weights[s]??'').trim()){alert('Introduce el peso de esta serie.');return}st.done[s]=!st.done[s];if(st.done[s]&&!st.reps[s])st.reps[s]=e[2];put(i,st);x.textContent=st.done[s]?'✓':'Hecha';x.closest('.seriesrow')?.classList.toggle('seriesdone',st.done[s]);if(st.done[s])startTimer(e[3],`timer${i}`)});
 document.querySelectorAll('[data-timer]').forEach(x=>x.onclick=()=>{const i=Number(x.dataset.timer);startTimer(r.ex[i][3],`timer${i}`)});
 document.querySelectorAll('[data-saveex]').forEach(x=>x.onclick=()=>{const i=Number(x.dataset.saveex),e=r.ex[i],st=getState(i);if(st.weights.some(v=>!String(v??'').trim())){alert('Introduce el peso de todas las series.');return}if(st.reps.some(v=>!String(v??'').trim())){alert('Completa las repeticiones de todas las series.');return}if(!String(st.rir).trim()){alert('Introduce el RIR final.');return}st.completed=true;st.done=Array(e[1]).fill(true);put(i,st);renderToday(day)});
}
function renderWeek(){setTitle('Semana');document.getElementById('app').innerHTML=`<div class='card'><div class='section-title'><h2>Semana</h2><span>elige día</span></div><div class='daygrid'>${Object.entries(ROUTINE).map(([d,r])=>`<button class='daybtn ${d===selected?'active':''}' data-day='${d}'>${d}: ${r.name}</button>`).join('')}</div></div><div id='day'></div>`;document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{selected=b.dataset.day;renderWeek()});renderDayPreview()}
function renderDayPreview(){const r=ROUTINE[selected],el=document.getElementById('day');el.innerHTML=`<div class='card'><div class='section-title'><h2>${r.name}</h2><span>${r.nutrition}</span></div>${r.ex.map(e=>`<p><b>${e[0]}</b> — ${e[1]}×${e[2]}</p>`).join('')||'<p class="muted">Descanso</p>'}<button id='trainSelected' class='primary wide'>Registrar este entrenamiento</button></div>`;document.getElementById('trainSelected').onclick=()=>{view='today';renderToday(selected);syncNav()}}
function renderHistory(){setTitle('Historial');const h=load(),dates=Object.keys(h).sort().reverse();document.getElementById('app').innerHTML=`<div class='card'><div class='section-title'><h2>Historial</h2><span>${dates.length} días</span></div>${dates.length?dates.map(d=>`<div class='hist block'><b>${d} · ${h[d].day}</b>${Object.entries(h[d].ex||{}).filter(([,v])=>v.completed).map(([n,v])=>`<div>${n}: ${displayWeights(v)} kg · ${(v.reps||[]).join('/')} · RIR ${v.rir||'-'}</div>`).join('')}</div>`).join(''):'<p class="muted">Todavía no hay entrenamientos guardados.</p>'}</div>`}
function renderProgress(){setTitle('Progreso');const names=[...new Set(Object.values(ROUTINE).flatMap(d=>d.ex.map(e=>e[0])))];const cards=names.map(n=>{const a=allFor(n);if(!a.length)return'';const last=a[a.length-1],first=a[0],delta=topWeight(last[1])-topWeight(first[1]),recent=a.slice(-6).reverse();return `<div class='card'><div class='exhead'><h3>${n}</h3><span class='badge'>${topWeight(last[1])||'-'} kg</span></div><p class='muted'>Cambio desde el primer registro: ${delta>0?'+':''}${delta.toFixed(1)} kg</p>${recent.map(([d,v])=>`<div class='progressrow'><span>${d}</span><b>${displayWeights(v)} kg · ${(v.reps||[]).join('/')}</b></div>`).join('')}</div>`}).join('');document.getElementById('app').innerHTML=`<section class='hero'><div class='eyebrow'>EVOLUCIÓN</div><h2>Progreso</h2><p>Cargas y repeticiones por ejercicio</p></section>${cards||'<div class="card"><p class="muted">Guarda tu primer entrenamiento para ver la evolución.</p></div>'}`}
function setTitle(t){const el=document.getElementById('pageTitle');if(el)el.textContent=t}
function syncNav(){document.querySelectorAll('nav button[data-v]').forEach(b=>b.classList.toggle('active',b.dataset.v===view))}
function render(){if(view==='today'){selected=days[new Date().getDay()];renderToday(selected)}else if(view==='week')renderWeek();else if(view==='history')renderHistory();else if(view==='progress')renderProgress();syncNav()}
document.querySelectorAll('nav button[data-v]').forEach(b=>b.onclick=()=>{view=b.dataset.v;render()});
const NUTRITION_URL='https://joaquincabral-wq.github.io/Nutrition/';
const nutritionBtn=document.getElementById('openNutrition');if(nutritionBtn)nutritionBtn.onclick=()=>{window.location.href=NUTRITION_URL};
render();
