const ROUTINE={
 lunes:{name:'PUSH',nutrition:'Fuerza · 2300 kcal',ex:[['Press inclinado mancuernas',4,8,150],['Press convergente máquina',3,10,150],['Press militar máquina/Smith',3,8,150],['Elevaciones laterales',4,12,90],['Aperturas peck-deck/polea',2,15,90],['Tríceps polea',3,10,120],['Tríceps sobre cabeza',3,12,120]]},
 martes:{name:'PULL',nutrition:'HC alto · 2450 kcal',ex:[['Jalón pronado abierto',4,8,150],['Remo con pecho apoyado',4,10,150],['Jalón neutro/cerrado',3,10,150],['Jalón brazos rectos',2,12,90],['Reverse peck-deck',4,15,90],['Curl inclinado',3,10,120],['Curl Scott',3,12,120]]},
 miércoles:{name:'LEGS',nutrition:'HC alto · 2450 kcal',ex:[['Hack / prensa',4,8,150],['Búlgara',3,10,150],['Extensión cuádriceps',3,12,90],['Curl femoral',4,10,150],['Hip thrust',3,10,150],['Gemelos',4,15,90],['Rueda abdominal',4,10,90]]},
 jueves:{name:'UPPER',nutrition:'Fuerza · 2300 kcal',ex:[['Press plano mancuernas',4,8,150],['Jalón',3,10,150],['Press inclinado/convergente',3,10,150],['Remo máquina/polea',4,10,150],['Elevaciones laterales',4,15,90],['Reverse peck-deck',3,15,90],['Curl bíceps',3,10,120],['Tríceps polea',3,10,120]]},
 viernes:{name:'LOWER + HOMBRO/BRAZO',nutrition:'HC alto · 2450 kcal',ex:[['Prensa',3,10,150],['Curl femoral',3,10,150],['Hip thrust',3,10,150],['Extensión cuádriceps',2,15,90],['Elevaciones laterales',4,15,90],['Curl martillo',3,12,120],['Tríceps cuerda',3,12,120],['Gemelos',3,15,90],['Rueda abdominal',3,10,90]]},
 sábado:{name:'DESCANSO',nutrition:'Descanso · 2150 kcal',ex:[]},domingo:{name:'DESCANSO',nutrition:'Descanso · 2150 kcal',ex:[]}}
const days=['domingo','lunes','martes','miércoles','jueves','viernes','sábado'];let view='today',selected=days[new Date().getDay()];
const key='jcTrainingHistoryV1';const load=()=>JSON.parse(localStorage.getItem(key)||'{}');const save=x=>localStorage.setItem(key,JSON.stringify(x));const iso=()=>new Date().toISOString().slice(0,10);
function lastFor(name){const h=load(),all=[];Object.entries(h).forEach(([d,s])=>Object.entries(s.ex||{}).forEach(([n,v])=>{if(n===name)all.push([d,v])}));all.sort((a,b)=>b[0].localeCompare(a[0]));return all[0]||null}
function advice(ex,last){if(!last)return 'Primera sesión: elige una carga que permita completar las repeticiones con RIR 1–2.';const v=last[1],ok=(v.reps||[]).length===ex[1]&&(v.reps||[]).every(r=>Number(r)>=ex[2])&&Number(v.rir||2)>=1;return ok?'✓ Objetivo completado: próxima sesión puedes subir al siguiente peso disponible.':'→ Mantén el peso hasta completar todas las series con buena técnica.'}
let timerInt=null;function startTimer(sec,id){clearInterval(timerInt);let t=sec;const el=document.getElementById(id);const draw=()=>el.textContent=`⏱ ${Math.floor(t/60)}:${String(t%60).padStart(2,'0')}`;draw();timerInt=setInterval(()=>{t--;draw();if(t<=0){clearInterval(timerInt);el.textContent='✓ Descanso terminado';navigator.vibrate?.(250)}},1000)}
function renderToday(day=selected){const r=ROUTINE[day],date=iso(),h=load(),today=h[date]||{day,ex:{}};let html=`<section class='hero'><div class='muted'>${day.toUpperCase()}</div><h1>${r.name}</h1><div>${r.nutrition}</div></section>`;if(!r.ex.length){html+=`<div class='card'><b>Día de descanso.</b><p class='muted'>Recuperación, paseo o LISS suave si corresponde.</p></div>`}r.ex.forEach((e,i)=>{const [name,sets,reps,rest]=e,last=lastFor(name),cur=today.ex[name]||{weight:'',reps:Array(sets).fill(''),rir:''};html+=`<div class='exercise' data-ex='${i}'><h3>${name}</h3><div class='target'>${sets} × ${reps}</div><div class='muted'>Descanso ${Math.floor(rest/60)}:${String(rest%60).padStart(2,'0')}</div>${last?`<div class='hist'>Anterior: <b>${last[1].weight||'-'} kg</b> · ${(last[1].reps||[]).join('/')||'-'} · RIR ${last[1].rir||'-'}</div>`:''}<div class='row'>Peso <input inputmode='decimal' data-weight='${i}' value='${cur.weight}'/> kg</div><div class='row'>${Array.from({length:sets},(_,s)=>`S${s+1}<input inputmode='numeric' data-rep='${i}:${s}' value='${cur.reps[s]||''}' placeholder='${reps}'>`).join('')}</div><div class='row'>RIR final <input inputmode='numeric' data-rir='${i}' value='${cur.rir}' placeholder='1-2'><button data-timer='${i}' class='primary'>Descanso</button><span class='timer' id='timer${i}'></span></div><div class='advice'>${advice(e,last)}</div></div>`});document.getElementById('app').innerHTML=html;bind(day,date)}
function bind(day,date){const r=ROUTINE[day];document.querySelectorAll('[data-weight]').forEach(x=>x.onchange=()=>upd(Number(x.dataset.weight),'weight',x.value));document.querySelectorAll('[data-rir]').forEach(x=>x.onchange=()=>upd(Number(x.dataset.rir),'rir',x.value));document.querySelectorAll('[data-rep]').forEach(x=>x.onchange=()=>{const [i,s]=x.dataset.rep.split(':').map(Number);upd(i,'rep',x.value,s)});document.querySelectorAll('[data-timer]').forEach(x=>x.onclick=()=>{const i=Number(x.dataset.timer);startTimer(r.ex[i][3],`timer${i}`)});function upd(i,type,val,s){const h=load();if(!h[date])h[date]={day,ex:{}};const e=r.ex[i],name=e[0];if(!h[date].ex[name])h[date].ex[name]={weight:'',reps:Array(e[1]).fill(''),rir:''};if(type==='rep')h[date].ex[name].reps[s]=val;else h[date].ex[name][type]=val;save(h)}}
function renderWeek(){document.getElementById('app').innerHTML=`<div class='card'><h2>Semana</h2>${Object.entries(ROUTINE).map(([d,r])=>`<button class='daybtn ${d===selected?'active':''}' data-day='${d}'>${d}: ${r.name}</button>`).join('')}</div><div id='day'></div>`;document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{selected=b.dataset.day;renderWeek();renderDayPreview()});renderDayPreview()}
function renderDayPreview(){const r=ROUTINE[selected],el=document.getElementById('day');el.innerHTML=`<div class='card'><h2>${r.name}</h2><p>${r.nutrition}</p>${r.ex.map(e=>`<p><b>${e[0]}</b> — ${e[1]}×${e[2]}</p>`).join('')}</div>`}
function renderHistory(){const h=load(),dates=Object.keys(h).sort().reverse();document.getElementById('app').innerHTML=`<div class='card'><h2>Historial</h2>${dates.length?dates.map(d=>`<div class='hist'><b>${d} · ${h[d].day}</b>${Object.entries(h[d].ex||{}).map(([n,v])=>`<div>${n}: ${v.weight||'-'} kg · ${(v.reps||[]).join('/')} · RIR ${v.rir||'-'}</div>`).join('')}</div>`).join(''):'<p class="muted">Todavía no hay entrenamientos guardados.</p>'}</div>`}
function render(){if(view==='today'){selected=days[new Date().getDay()];renderToday()}else if(view==='week')renderWeek();else renderHistory()}document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.v;render()});render();
